---
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: p10k-openbsd
    box: pygolo/openbsd7
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
  inventory:
    host_vars:
      p10k-openbsd:
        ansible_python_interpreter: /usr/local/bin/python3
