---
- name: Prepare
  hosts: all
  become: true
  roles:
    - role: diodonfrost.update_package_manager_cache
  tasks:
    - name: Linux | Create test users
      ansible.builtin.user:
        name: "{{ item }}"
      loop:
        - foo
        - bar
