---
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: p10k-freebsd
    box: generic/freebsd14
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
verifier:
  name: ansible
